language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t sujoymodak/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true sujoymodak/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-974600987815"
  bucker_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY