language: node_js
sudo: required
services:
  - docker
before_install:
  - docker build -t sujoymodak/docker-react -f Dockerfile.dev .
  script:
  - docker run -e CI=true sujoymodak/docker-react npm run test
